# site.yml — One-command cluster bring-up with kubeadm + containerd + Calico
# Run with: ansible-playbook -i inventory/hosts.ini site.yml -b

- name: Prepare OS on all nodes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Ensure apt prerequisites present (Ubuntu)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Disable swap immediately
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | int > 0

    - name: Disable swap permanently in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'

    - name: Configure kernel modules persistence
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Load required kernel modules now
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl params for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'
      notify: Reload sysctl

  handlers:
    - name: Reload sysctl
      ansible.builtin.command: sysctl --system

# ------------------------------------------------------------------------------------

- name: Install and configure containerd on all nodes
  hosts: k8s_cluster
  become: true
  vars:
    containerd_config: /etc/containerd/config.toml
  tasks:
    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create default containerd configuration if missing
      ansible.builtin.shell: |
        test -f {{ containerd_config }} || (mkdir -p /etc/containerd && containerd config default > {{ containerd_config }})
      args:
        creates: "{{ containerd_config }}"

    - name: Ensure SystemdCgroup is enabled in containerd
      ansible.builtin.replace:
        path: "{{ containerd_config }}"
        regexp: '^\s*SystemdCgroup = false'
        replace: '    SystemdCgroup = true'

    - name: Restart and enable containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true
        daemon_reload: true

# ------------------------------------------------------------------------------------

- name: Install Kubernetes packages on all nodes
  hosts: k8s_cluster
  become: true
  vars:
    k8s_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  tasks:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes apt repo key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor }}/deb/Release.key | \
          gpg --dearmor -o {{ k8s_keyring }}
      args:
        creates: "{{ k8s_keyring }}"

    - name: Add Kubernetes apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by={{ k8s_keyring }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor }}/deb/ /
        owner: root
        group: root
        mode: '0644'

    - name: Install kubelet, kubeadm, kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      ansible.builtin.shell: apt-mark hold kubelet kubeadm kubectl
      changed_when: false

    - name: Enable kubelet service (will remain inactive until kubeadm init/join)
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

# ------------------------------------------------------------------------------------

- name: Initialize control plane
  hosts: kube_control_plane
  become: true
  vars:
    kubeadm_init_args: "--pod-network-cidr={{ pod_network_cidr }}"
  tasks:
    - name: Check if cluster is already initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_adminconf

    - name: kubeadm init
      ansible.builtin.command: kubeadm init {{ kubeadm_init_args }}
      when: not k8s_adminconf.stat.exists
      register: kubeadm_init_out
      changed_when: not k8s_adminconf.stat.exists

    - name: Export kubeconfig to root (admin.conf)
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: '0700'

    - name: Copy kubeconfig to root
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true
        mode: '0600'

    - name: Copy kubeconfig to Ansible SSH user for convenience
      become_user: "{{ ansible_user_id }}"
      ansible.builtin.shell: |
        mkdir -p "$HOME/.kube"
        sudo cp -f /etc/kubernetes/admin.conf "$HOME/.kube/config"
        sudo chown "$(id -u)":"$(id -g)" "$HOME/.kube/config"
      args:
        executable: /bin/bash

    - name: Create (or refresh) join command token
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_cmd

    - name: Set join command fact on control host
      ansible.builtin.set_fact:
        kube_join_cmd: "{{ join_cmd.stdout | trim }}"

# ------------------------------------------------------------------------------------

- name: Install CNI (Calico) on control plane
  hosts: kube_control_plane
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  vars:
    calico_manifest: /tmp/calico.yaml
    calico_marker: /etc/kubernetes/.calico_applied
    # Auto-detect interface - can be overridden in group_vars
    calico_ip_autodetect_method: "interface={{ ansible_default_ipv4.interface }}"
  tasks:
    - name: Download Calico manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
        dest: "{{ calico_manifest }}"
        mode: '0644'

    - name: Check if IP_AUTODETECTION_METHOD is commented in manifest
      ansible.builtin.shell: grep -n "# - name: IP_AUTODETECTION_METHOD" {{ calico_manifest }} || true
      register: ip_autodetect_check
      changed_when: false

    - name: Uncomment IP_AUTODETECTION_METHOD in Calico manifest
      ansible.builtin.replace:
        path: "{{ calico_manifest }}"
        regexp: '(\s+)# - name: IP_AUTODETECTION_METHOD'
        replace: '\1- name: IP_AUTODETECTION_METHOD'
      when: ip_autodetect_check.stdout != ""

    - name: Set IP_AUTODETECTION_METHOD value in Calico manifest
      ansible.builtin.replace:
        path: "{{ calico_manifest }}"
        regexp: '(\s+)#   value: "interface=.*"'
        replace: '\1  value: "{{ calico_ip_autodetect_method }}"'
      when: ip_autodetect_check.stdout != ""

    - name: Apply Calico manifest
      ansible.builtin.command: kubectl apply -f {{ calico_manifest }}
      register: calico_apply
      changed_when: "'created' in calico_apply.stdout or 'configured' in calico_apply.stdout"

    - name: Mark Calico applied (idempotence marker)
      ansible.builtin.file:
        path: "{{ calico_marker }}"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Wait for calico-node DaemonSet to be Ready
      ansible.builtin.command: kubectl -n kube-system rollout status ds/calico-node --timeout=300s
      register: calico_rollout
      changed_when: false

    - name: Verify Calico pods are running
      ansible.builtin.shell: |
        kubectl get pods -n kube-system -l k8s-app=calico-node -o wide
      register: calico_pods
      changed_when: false

    - name: Display Calico pod status
      ansible.builtin.debug:
        var: calico_pods.stdout_lines

# ------------------------------------------------------------------------------------

- name: Join worker nodes to the cluster
  hosts: kube_workers
  become: true
  vars:
    control_host: "{{ groups['kube_control_plane'][0] }}"
  tasks:
    - name: Read join command from control plane hostvars
      ansible.builtin.set_fact:
        kube_join_cmd: "{{ hostvars[control_host].kube_join_cmd }}"
      when: hostvars[control_host].kube_join_cmd is defined

    - name: Fail if join command is missing
      ansible.builtin.fail:
        msg: "kube_join_cmd is not available from the control plane. Re-run the play or check previous plays for errors."
      when: kube_join_cmd is not defined

    - name: Join the node to the cluster
      ansible.builtin.command: "{{ kube_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

# ------------------------------------------------------------------------------------

- name: Verify cluster from control-plane
  hosts: kube_control_plane
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Wait for nodes to become Ready
      ansible.builtin.shell: |
        set -e
        for i in {1..30}; do
          NOT_READY=$(kubectl get nodes --no-headers 2>/dev/null | awk '$2!="Ready" {print $1}' | wc -l)
          if [ "$NOT_READY" -eq 0 ]; then exit 0; fi
          sleep 10
        done
        kubectl get nodes
        exit 1
      args:
        executable: /bin/bash

    - name: Show nodes
      ansible.builtin.command: kubectl get nodes -o wide
      register: nodes_out

    - name: Display nodes
      ansible.builtin.debug:
        var: nodes_out.stdout_lines

    - name: Show all pods in kube-system
      ansible.builtin.command: kubectl get pods -n kube-system -o wide
      register: pods_out

    - name: Display kube-system pods
      ansible.builtin.debug:
        var: pods_out.stdout_lines
