# site.yml — One-command Kubernetes cluster bring-up
# Run with:
# ansible-playbook -i inventory/hosts.ini site.yml -b

###############################################################################
# GLOBAL VARIABLES
###############################################################################
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Define global variables
      ansible.builtin.set_fact:
        kubernetes_minor: "v1.29"
        pod_network_cidr: "192.168.0.0/16"

###############################################################################
# PREPARE OS (ALL NODES)
###############################################################################
- name: Prepare OS on all nodes
  hosts: controllers:workers
  become: true

  tasks:
    - name: Install OS prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Disable swap immediately
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | int > 0

    - name: Disable swap permanently
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'

    - name: Load kernel modules config
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Load kernel modules
      ansible.builtin.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                = 1
        mode: '0644'
      notify: Reload sysctl

  handlers:
    - name: Reload sysctl
      ansible.builtin.command: sysctl --system

###############################################################################
# CONTAINERD
###############################################################################
- name: Install and configure containerd
  hosts: controllers:workers
  become: true

  tasks:
    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present
        update_cache: yes

    # 👇 ensure the destination directory exists
    - name: Ensure /etc/containerd exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate containerd default config
      ansible.builtin.command: containerd config default
      register: containerd_default
      changed_when: false

    - name: Write containerd config
      ansible.builtin.copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_default.stdout }}"
        mode: '0644'

    - name: Enable SystemdCgroup
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true

###############################################################################
# KUBERNETES PACKAGES
###############################################################################
- name: Install Kubernetes components
  hosts: controllers:workers
  become: true

  vars:
    k8s_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  tasks:
    - name: Ensure keyrings dir exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes repo key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor }}/deb/Release.key |
        gpg --dearmor -o {{ k8s_keyring }}
      args:
        creates: "{{ k8s_keyring }}"

    - name: Add Kubernetes repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by={{ k8s_keyring }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor }}/deb/ /
        mode: '0644'

    - name: Install kubeadm, kubelet, kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl
      changed_when: false

###############################################################################
# CONTROL PLANE INIT
###############################################################################
- name: Initialize Kubernetes control plane
  hosts: controllers
  become: true

  tasks:
    - name: Check if cluster already initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_adminconf

    - name: kubeadm init
      ansible.builtin.command: >
        kubeadm init
        --pod-network-cidr={{ pod_network_cidr }}
      when: not k8s_adminconf.stat.exists
      register: kubeadm_out

    - name: Configure kubeconfig for root
      ansible.builtin.shell: |
        mkdir -p /root/.kube
        cp /etc/kubernetes/admin.conf /root/.kube/config
        chmod 600 /root/.kube/config

    - name: Create join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Set join command fact
      ansible.builtin.set_fact:
        kube_join_cmd: "{{ join_cmd.stdout }}"

###############################################################################
# CALICO CNI
###############################################################################
- name: Install Calico CNI
  hosts: controllers
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  vars:
    calico_marker: /etc/kubernetes/.calico_installed

  tasks:
    - name: Check if Calico already installed
      ansible.builtin.stat:
        path: "{{ calico_marker }}"
      register: calico_done

    - name: Apply Calico
      ansible.builtin.command: >
        kubectl apply -f
        https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
      when: not calico_done.stat.exists

    - name: Mark Calico installed
      ansible.builtin.file:
        path: "{{ calico_marker }}"
        state: touch
      when: not calico_done.stat.exists

###############################################################################
# JOIN WORKERS
###############################################################################
- name: Join worker nodes
  hosts: workers
  become: true

  tasks:
    - name: Join cluster
      ansible.builtin.command: "{{ hostvars[groups['controllers'][0]].kube_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

###############################################################################
# VERIFY CLUSTER
###############################################################################
- name: Verify cluster
  hosts: controllers
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Show nodes
      ansible.builtin.command: kubectl get nodes -o wide
      register: nodes

    - name: Display nodes
      ansible.builtin.debug:
        var: nodes.stdout_lines
